# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CHOWRAID
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is where all my github projects are housed. feel free to use any of the projects that are on my github.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chowraid.com" # the base hostname & protocol for your site
twitter_username: chowraid
github_username:  chowraid

# Build settings
markdown: kramdown
